using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DigiTransac.Api.Models;

public enum ChatMessageType
{
    Text,           // Regular text message
    Transaction,    // Reference to a P2P transaction
    Request         // Money request (future feature)
}

public enum MessageStatus
{
    Sent,       // Message sent but not yet delivered
    Delivered,  // Message delivered to recipient's device
    Read        // Message read by recipient
}

[BsonIgnoreExtraElements]
public class ChatMessage
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = null!;

    /// <summary>
    /// The user who sent this message
    /// </summary>
    [BsonElement("senderUserId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string SenderUserId { get; set; } = null!;

    /// <summary>
    /// The user who receives this message
    /// </summary>
    [BsonElement("recipientUserId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string RecipientUserId { get; set; } = null!;

    /// <summary>
    /// Type of message: Text, Transaction reference, or Request
    /// </summary>
    [BsonElement("type")]
    [BsonRepresentation(BsonType.String)]
    public ChatMessageType Type { get; set; } = ChatMessageType.Text;

    /// <summary>
    /// Text content (for Text type messages)
    /// </summary>
    [BsonElement("content")]
    public string? Content { get; set; }

    /// <summary>
    /// Reference to transaction (for Transaction type messages).
    /// All transaction data (amount, currency, status, source, etc.) is fetched from Transaction.
    /// </summary>
    [BsonElement("transactionId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? TransactionId { get; set; }

    /// <summary>
    /// ID of message this is replying to (for threaded replies)
    /// </summary>
    [BsonElement("replyToMessageId")]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? ReplyToMessageId { get; set; }

    /// <summary>
    /// Message delivery/read status
    /// </summary>
    [BsonElement("status")]
    [BsonRepresentation(BsonType.String)]
    public MessageStatus Status { get; set; } = MessageStatus.Sent;

    /// <summary>
    /// When the message was delivered to recipient
    /// </summary>
    [BsonElement("deliveredAt")]
    public DateTime? DeliveredAt { get; set; }

    /// <summary>
    /// When the message was read by recipient
    /// </summary>
    [BsonElement("readAt")]
    public DateTime? ReadAt { get; set; }

    /// <summary>
    /// Whether the message has been edited
    /// </summary>
    [BsonElement("isEdited")]
    public bool IsEdited { get; set; } = false;

    /// <summary>
    /// When the message was last edited
    /// </summary>
    [BsonElement("editedAt")]
    public DateTime? EditedAt { get; set; }

    /// <summary>
    /// Whether the message has been deleted (soft delete)
    /// </summary>
    [BsonElement("isDeleted")]
    public bool IsDeleted { get; set; } = false;

    /// <summary>
    /// When the message was deleted
    /// </summary>
    [BsonElement("deletedAt")]
    public DateTime? DeletedAt { get; set; }

    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // === Activity Feed / System Message Fields ===

    /// <summary>
    /// True if this message was auto-generated by the system (e.g., transaction confirmed, recurring, import)
    /// </summary>
    [BsonElement("isSystemGenerated")]
    public bool IsSystemGenerated { get; set; } = false;

    /// <summary>
    /// Source of the system-generated message for display purposes
    /// Values: "TransactionConfirmed", "TransactionDeclined", "TransactionEdited", "Recurring", "Import", "Transfer"
    /// </summary>
    [BsonElement("systemSource")]
    public string? SystemSource { get; set; }
}

/// <summary>
/// Known system sources for activity feed messages
/// </summary>
public static class SystemMessageSources
{
    public const string TransactionConfirmed = "TransactionConfirmed";
    public const string TransactionDeclined = "TransactionDeclined";
    public const string TransactionEdited = "TransactionEdited";
    public const string Recurring = "Recurring";
    public const string Import = "Import";
    public const string Transfer = "Transfer";
}
