/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// NEVER cache auth endpoints — these must always go to the network
registerRoute(
  /^https?:\/\/.*\/api\/auth\//,
  new NetworkFirst({
    cacheName: 'auth-no-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [] }), // Cache nothing
    ],
  })
);

// Runtime caching for API calls
registerRoute(
  /^https?:\/\/.*\/api\/transactions/,
  new NetworkFirst({
    cacheName: 'transactions-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

registerRoute(
  /^https?:\/\/.*\/api\/labels/,
  new NetworkFirst({
    cacheName: 'labels-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 7 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

registerRoute(
  /^https?:\/\/.*\/api\/accounts/,
  new NetworkFirst({
    cacheName: 'accounts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

registerRoute(
  /^https?:\/\/.*\/api\/budgets/,
  new NetworkFirst({
    cacheName: 'budgets-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 12 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

registerRoute(
  /^https?:\/\/.*\/api\/conversations/,
  new NetworkFirst({
    cacheName: 'conversations-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

registerRoute(
  /^https?:\/\/.*\/api\/dashboard/,
  new NetworkFirst({
    cacheName: 'dashboard-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
    networkTimeoutSeconds: 10,
  })
);

// QR code caching
registerRoute(
  /^https:\/\/api\.qrserver\.com/,
  new CacheFirst({
    cacheName: 'qr-code-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 30 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// Map tiles caching
registerRoute(
  /^https:\/\/[a-z]\.tile\.openstreetmap\.org/,
  new CacheFirst({
    cacheName: 'map-tiles-osm',
    plugins: [
      new ExpirationPlugin({ maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

registerRoute(
  /^https:\/\/[a-z]\.basemaps\.cartocdn\.com/,
  new CacheFirst({
    cacheName: 'map-tiles-carto',
    plugins: [
      new ExpirationPlugin({ maxEntries: 500, maxAgeSeconds: 60 * 60 * 24 * 30 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

registerRoute(
  /^https:\/\/nominatim\.openstreetmap\.org/,
  new CacheFirst({
    cacheName: 'geocoding-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 7 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// =============================================================================
// PUSH NOTIFICATION HANDLING
// =============================================================================

interface PushNotificationPayload {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: {
    url?: string;
    [key: string]: unknown;
  };
}

/**
 * Handle incoming push notifications
 */
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push notification received:', event);

  let payload: PushNotificationPayload = {
    title: 'DigiTransac',
    body: 'You have a new notification',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-72x72.png',
  };

  // Parse the push data if available
  if (event.data) {
    try {
      const data = event.data.json() as PushNotificationPayload;
      payload = {
        title: data.title || payload.title,
        body: data.body || payload.body,
        icon: data.icon || payload.icon,
        badge: data.badge || payload.badge,
        tag: data.tag,
        data: data.data,
      };
    } catch (error) {
      console.error('[SW] Error parsing push data:', error);
      // Fall back to text content
      const text = event.data.text();
      if (text) {
        payload.body = text;
      }
    }
  }

  // Show the notification
  // Note: Using type assertion since service worker notification options include more properties
  const notificationPromise = self.registration.showNotification(payload.title, {
    body: payload.body,
    icon: payload.icon,
    badge: payload.badge,
    tag: payload.tag || 'default',
    data: payload.data,
    requireInteraction: false,
  } as NotificationOptions);

  event.waitUntil(notificationPromise);
});

/**
 * Handle notification click events
 */
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification clicked:', event);

  // Close the notification
  event.notification.close();

  // Get the URL to open (from notification data or default to root)
  const notificationData = event.notification.data as { url?: string } | undefined;
  const urlToOpen = notificationData?.url || '/';

  // Open or focus the app window
  const openPromise = (async () => {
    const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
    
    // Check if a window is already open
    for (const client of clientList) {
      const windowClient = client as WindowClient;
      // Try to focus and navigate an existing window
      if (windowClient.url && 'focus' in windowClient) {
        try {
          await windowClient.navigate(urlToOpen);
          return windowClient.focus();
        } catch {
          // If navigate fails, just focus
          return windowClient.focus();
        }
      }
    }
    
    // If no window is open, open a new one
    return self.clients.openWindow(urlToOpen);
  })();

  event.waitUntil(openPromise);
});

/**
 * Handle notification close events (for analytics)
 */
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  console.log('[SW] Notification closed:', event.notification.tag);
});

/**
 * Handle push subscription change (e.g., browser updates the subscription)
 * Re-subscribes with the VAPID key from the server and syncs the new subscription.
 */
self.addEventListener('pushsubscriptionchange', (event) => {
  console.log('[SW] Push subscription changed');
  
  const apiBaseUrl = `${self.location.origin}/api`;
  
  const resubscribe = async () => {
    try {
      // Fetch the VAPID public key from the server
      const vapidResponse = await fetch(`${apiBaseUrl}/push/vapid-public-key`);
      if (!vapidResponse.ok) {
        console.error('[SW] Failed to fetch VAPID key:', vapidResponse.status);
        return;
      }
      const { publicKey } = await vapidResponse.json() as { publicKey: string | null };
      if (!publicKey) {
        console.error('[SW] No VAPID public key configured on server');
        return;
      }

      // Convert base64url VAPID key to Uint8Array
      const padding = '='.repeat((4 - (publicKey.length % 4)) % 4);
      const base64 = (publicKey + padding).replace(/-/g, '+').replace(/_/g, '/');
      const rawData = atob(base64);
      const applicationServerKey = new Uint8Array(rawData.length);
      for (let i = 0; i < rawData.length; i++) {
        applicationServerKey[i] = rawData.charCodeAt(i);
      }

      // Re-subscribe with the proper VAPID key
      const subscription = await self.registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });

      // Send the new subscription to the server
      const subscriptionJson = subscription.toJSON();
      const keys = subscriptionJson.keys as { p256dh: string; auth: string } | undefined;
      if (!keys) {
        console.error('[SW] Failed to get subscription keys after resubscribe');
        return;
      }

      const syncResponse = await fetch(`${apiBaseUrl}/push/subscribe`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          endpoint: subscription.endpoint,
          keys: { p256dh: keys.p256dh, auth: keys.auth },
          deviceName: 'Auto-resubscribed',
        }),
      });

      if (syncResponse.ok) {
        console.log('[SW] Resubscribed and synced with server');
      } else {
        console.error('[SW] Failed to sync subscription with server:', syncResponse.status);
      }
    } catch (error) {
      console.error('[SW] Failed to resubscribe to push notifications:', error);
    }
  };

  event.waitUntil(resubscribe());
});

console.log('[SW] Service worker initialized with push notification support');